language: r
warnings_are_errors: true
sudo: required

os:
  - linux
  - osx

install:
  # setup conda
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then MINICONDA_OS=Linux; else MINICONDA_OS=MacOSX; fi
  - wget https://repo.anaconda.com/miniconda/Miniconda3-latest-$MINICONDA_OS-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  # setup R packages
  - R -e 'install.packages("devtools")'
  - R -e 'devtools::install_deps(dep = T)'

script:
  - travis_wait 30 sudo R CMD build .
  - R CMD check *tar.gz
