---
title: "Fitting Timecourses"
author: "Sean R. Hackett"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Vignette Title}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup}
suppressPackageStartupMessages(library(dplyr))
suppressPackageStartupMessages(library(ggplot2))
library(tidyr)
library(purrr)
library(impulse)
theme_set(theme_bw() + theme(text = element_text(size = 15)))
```

```{r simulate_timecourses}
timecourses <- simulate_timecourses(n = 20)

# plot of timecourses + parameters
timecourses %>%
  tidyr::unnest(measurements) %>%
  tidyr::unite(label, true_model, tc_id) %>%
  ggplot(aes(x = time)) +
  geom_point(aes(y = abundance)) +
  geom_path(aes(y = sim_fit)) +
  facet_wrap(~ label)
```

## Estimate best fitting sigmoid and impulse model for each timecourse using TensorFlow

```{r estimate_parameters}
timecourse_parameters <- timecourses %>%
  unnest(measurements) %>%
  # separate by true model
  nest(-true_model, .key = "measurements") %>%
  # fit all models to each timecourse
  crossing(tibble(model = c("sigmoid", "impulse"))) %>%
  mutate(timecourse_list = map2(measurements, model, estimate_timecourse_params_tf, n_initializations = 50)) %>%
  # reduce each timecourse to best fitting model capturing uncertainty around the best minima
  mutate(best_timecourse_list = map(timecourse_list, reduce_best_timecourse_params, reduction_type = "loss-min")) %>%
  unnest(map(best_timecourse_list, ~ as_tibble(map(., list))))
```

```{r parameter_comparison}
estimated_parameters <- timecourse_parameters %>%
  filter(true_model == model) %>%
  unnest(parameters) %>%
  select(tc_id, variable, estimated_value = value)
  
true_parameters <- timecourses %>%
  select(-measurements) %>%
  unnest(params) %>%
  gather(variable, true_value, -true_model, -tc_id) %>%
  filter(!is.na(true_value))

true_parameters %>%
  left_join(estimated_parameters, by = c("tc_id", "variable")) %>%
  ggplot(aes(x = true_value, y = estimated_value)) +
  geom_point() +
  facet_wrap(~ true_model + variable, scale = "free", ncol = 5) +
  geom_abline(intercept = 0, slope = 1, color = "blue")
```

## Model comparison

```{r compare_models}
model_comparison <- timecourse_parameters %>%
  unnest(loss) %>%
  impulse_sigmoid_comparison(fdr_cutoff = 0.001) 

timecourses %>%
  select(tc_id, true_model) %>%
  left_join(model_comparison %>%
              select(tc_id, is_impulse),
            by = "tc_id") %>%
  count(true_model, is_impulse) %>%
  spread(true_model, n)
```

## Visualization comparison

```{r}
fitted_kinetics <- timecourse_parameters %>%
  unnest(parameters) %>%
  select(tc_id, model, variable, value) %>%
  spread(variable, value) %>%
  nest(-tc_id, .key = "fitted_kinetics")

augmented_timecourses <- timecourses %>%
  left_join(fitted_kinetics, by =  "tc_id") %>%
  left_join(model_comparison, by = "tc_id")

kinetics_plotting(augmented_timecourses, saturation = 0.9, max_time, fit_timepoints = 100)
```
